linters:
  enable-all: true

issues:
  exclude-rules:
    - path: \.go
      linters:
        - stylecheck
        - exhaustivestruct
        - typecheck
        - tagliatelle
        - nolintlint
    - path: _test\.go
      linters:
        - lll
        - dupl
        - funlen
        - gomnd
        - maligned

  exclude-use-default: false
