linters:
  enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - dupl
        - funlen
        - gomnd
        - maligned

  exclude-use-default: false
