name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: checkout code
        uses: actions/checkout@v2

      - name: run golangci-lint
        run: make lint

      - name: run tests
        run: make test

      - name: run tests
        run: make test
