name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: gokkan
          POSTGRES_PASSWORD: 1
          POSTGRES_USER: gokkan
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: checkout code
        uses: actions/checkout@v2

      - name: run golangci-lint
        run: make lint

      - name: run tests
        env:
          GOKKAN_DATABASE_HOST: postgres
        run: make test

      - name: run tests
        run: make test
